/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Anchor,
  IStoredPositionInfo,
} from './api/layout';

export namespace Components {
  interface AppHome {}
  interface AppRoot {}
  interface ControlContainer {
    'positionInfo': IStoredPositionInfo;
  }
  interface ControlEditor {}
  interface DesignEditor {
    'addControl': (name: string, layoutInfo: IStoredPositionInfo) => Promise<void>;
  }
  interface DragHandle {
    'anchorMode': Anchor;
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLControlContainerElement extends Components.ControlContainer, HTMLStencilElement {}
  var HTMLControlContainerElement: {
    prototype: HTMLControlContainerElement;
    new (): HTMLControlContainerElement;
  };

  interface HTMLControlEditorElement extends Components.ControlEditor, HTMLStencilElement {}
  var HTMLControlEditorElement: {
    prototype: HTMLControlEditorElement;
    new (): HTMLControlEditorElement;
  };

  interface HTMLDesignEditorElement extends Components.DesignEditor, HTMLStencilElement {}
  var HTMLDesignEditorElement: {
    prototype: HTMLDesignEditorElement;
    new (): HTMLDesignEditorElement;
  };

  interface HTMLDragHandleElement extends Components.DragHandle, HTMLStencilElement {}
  var HTMLDragHandleElement: {
    prototype: HTMLDragHandleElement;
    new (): HTMLDragHandleElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'control-container': HTMLControlContainerElement;
    'control-editor': HTMLControlEditorElement;
    'design-editor': HTMLDesignEditorElement;
    'drag-handle': HTMLDragHandleElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface AppRoot {}
  interface ControlContainer {
    'positionInfo'?: IStoredPositionInfo;
  }
  interface ControlEditor {}
  interface DesignEditor {}
  interface DragHandle {
    'anchorMode'?: Anchor;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-root': AppRoot;
    'control-container': ControlContainer;
    'control-editor': ControlEditor;
    'design-editor': DesignEditor;
    'drag-handle': DragHandle;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'control-container': LocalJSX.ControlContainer & JSXBase.HTMLAttributes<HTMLControlContainerElement>;
      'control-editor': LocalJSX.ControlEditor & JSXBase.HTMLAttributes<HTMLControlEditorElement>;
      'design-editor': LocalJSX.DesignEditor & JSXBase.HTMLAttributes<HTMLDesignEditorElement>;
      'drag-handle': LocalJSX.DragHandle & JSXBase.HTMLAttributes<HTMLDragHandleElement>;
    }
  }
}


